// Reference-derived pixel materials. Generated by tools/build-reference-art.py.
// Source: user-supplied dungeon reference, 1897 x 829; SHA-256 3e3c583694bbbe6edc4c94832ce4c9cd368f67dcbcbd9a33e7952aefb7a646bc.
// Native pixels, bounded palettes, nearest sampling, no dithering or runtime noise.
const ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
const DATA = {
  "floor": {
    "palette": [
      "#7d593e",
      "#78563c",
      "#74553d",
      "#75543c",
      "#73543c",
      "#72543d",
      "#75533b",
      "#73533b",
      "#72533c",
      "#72533b",
      "#72533a",
      "#71533c",
      "#74523a",
      "#72523b",
      "#71523b",
      "#71513a",
      "#6f523c",
      "#6e513c",
      "#6f5137",
      "#6e503b",
      "#6e4f34",
      "#6c503b",
      "#6b4f39",
      "#694f3b",
      "#6b4e3a",
      "#6c4e30",
      "#674d3a",
      "#654b37",
      "#604a39",
      "#5c4736",
      "#584637",
      "#534536",
      "#524233",
      "#4c4032",
      "#453d31",
      "#3d3731",
      "#363432",
      "#36342e",
      "#36322d",
      "#2e2f2f"
    ],
    "textures": [
      {
        "width": 16,
        "rows": [
          "llllllllllllllll",
          "lhBBBBBBBDBCBBBB",
          "lgHHHNKNHJHHGDDG",
          "lgJNJEJJJJJJJJJD",
          "lgJJHINHEFIEEFEH",
          "lgHJJNNJIHEFIFEH",
          "lgHJJJOJHIIEEIHG",
          "lgHHHHHHHIEHJIIN",
          "lgMNJJJHEEEEFIJN",
          "lfHKHDHDDEEEIILO",
          "lfHHHEDDEEEEIJNN",
          "lgHHHDHDDCEEFJNM",
          "lgGDEDDDHIEHEEEG",
          "lhGDDGHHHHFJEEEG",
          "liGHJNNHEHIJHGDC",
          "liDHOQQQLFFFFFCJ"
        ]
      },
      {
        "width": 16,
        "rows": [
          "llllllllllllllll",
          "lhVRRQQLFQQQQQQV",
          "lfGHHEIGCDCEHHHG",
          "leHJLHECDCCCDEDH",
          "lfJJIHHIEEECCEEH",
          "leHJJHFHCECCCEEH",
          "leNJHFIEDCDCFEEC",
          "leJJHHGDECCCCCCC",
          "leHJHGHHECEEECCC",
          "leHHHGHDCCCCCCCC",
          "leDDDDDDDCCCCCDD",
          "leGDDDDCDCCCCCCD",
          "leDDEDDCDCCCDCDC",
          "lfDGDDCDCCCDDDDD",
          "lfDDCCCEEEEIEEDD",
          "lgBBBCCCCCFFFCCA"
        ]
      },
      {
        "width": 16,
        "rows": [
          "llllllllllllllll",
          "leQQQRRVRVWVRRRT",
          "leNNOOOQOPOJJJNA",
          "leLLLOOONOOLLOBA",
          "leNOLLOIILLLLLGA",
          "leNNIHHONOIHLKDA",
          "leNOIHNNNOIEJJDA",
          "leHJNKKNLJJHJJDA",
          "leHNJJMKNHJNJEDA",
          "leHJJJJHHNJHNHDA",
          "leHNJHNNMKNHNHDA",
          "leHNIKNHNKKHHGBA",
          "leGJJKKONPNHJHDA",
          "leMNNNOONJHHKHDA",
          "lhMNOPPOPONHHHGA",
          "lhBCCLLOHEDDDCBA"
        ]
      },
      {
        "width": 16,
        "rows": [
          "llllllllllllllll",
          "ldYRLFFFLRWYaabh",
          "lcNNJHDHMPPPTOTh",
          "lbONOONOPPPOOQOe",
          "lcPPOOPPOLLJHHNf",
          "lcPPPOIIIILOEIIe",
          "lcPNOLILNNOIFIOf",
          "lcPPOINKJIOIIIIe",
          "lcNNONHJNHJJNHIf",
          "lcNNNNNHHJHHFIIf",
          "lcJIJJJHNNNNHHNf",
          "lcHHHNHHHHHJFHHf",
          "lcHNNHDDHJHHIHDf",
          "lcHHHGMMHILHRTNf",
          "lePNNIGHNNILLQRi",
          "lcCCFFCDCBCCCCCh"
        ]
      },
      {
        "width": 16,
        "rows": [
          "llllllllllllllll",
          "ljgbbbbccbbbccfe",
          "ljeBBCDELCBBBCbW",
          "liRILeegheefXCCC",
          "liTIQeggheefRCCC",
          "lhPPajXXXXXXhCCC",
          "lhPPXiXXXXXXhCCC",
          "lhPQWcXaXXXXcCDH",
          "lhPOXdaaaXXXeCDD",
          "lhPPWdaaaXXVfCBC",
          "lhPOTgaaaYXVfCDD",
          "lgOQRhggffeeeCCC",
          "lgOQRehhhfffRCEE",
          "lgOOINNLIDDDHJFJ",
          "ljeBCDIQQRRTTThg",
          "ljdAAAABBEFPPTge"
        ]
      },
      {
        "width": 16,
        "rows": [
          "llllllllllllllll",
          "ljdCBBCCLTTTHHee",
          "liaAAABAABBGGGcb",
          "lfBFVXahiccDGGGB",
          "lfGIRXaficcCENPG",
          "lgGPchVXVXXefQTH",
          "lfDNXfVXXaaegPPH",
          "lfDHXcaaaaaceTTH",
          "lfBEVcaaaaXcfOPG",
          "lfDFXcaaaXXehLPG",
          "lfDNXeaaaaafhOTH",
          "lfGGbghhhihhhJNG",
          "lgDHFXddddeVFSPG",
          "lgDCIOTTTTYTPPPG",
          "ljgTTQTOQOPPPSgg",
          "ljeQRSOHCDBBBDed"
        ]
      },
      {
        "width": 16,
        "rows": [
          "llllllllllllllll",
          "ljhaaaXcedddddjj",
          "ligAAAAXePPNJPdg",
          "lhHbdeefeeeedaEB",
          "lgMdeeeeeeeeecMB",
          "lgMgeeeeeeeeedMB",
          "lgMeeeeeeeeeeeGA",
          "lgGeeeeeeeeeeeDB",
          "lgDeeeeeeeeeeeDB",
          "lgDeeeeeeeeeedDB",
          "lgBeeeeeeeeeeeGB",
          "lfBeedeeeeeeeeGB",
          "lfBWQXcdeeeeYGGB",
          "lfBWQaddgeedbGBA",
          "ljgCENHNHDDBDMed",
          "ljhaaaXVRQRRTWfh"
        ]
      },
      {
        "width": 16,
        "rows": [
          "llllllllllllllll",
          "lhdAAAAAAAAAAAAA",
          "lfbAAABBBBBBBBAA",
          "ldAYWWWWWYYVVVAA",
          "ldAWWWWWYYVVVVAA",
          "leAWYWVVVVVVYVAA",
          "ldAYWVVTRTVVVVAA",
          "leAYVTRTRTVVVVAA",
          "leBYTTTTRVVYVVAA",
          "leGTTVTTRTVYWWAA",
          "ldAYTTVVTVVVadAA",
          "ldATWTVVVYYVdfAA",
          "ldATTTVadXcgecAA",
          "ldAWWYYXdbcfdcAA",
          "ljeAABBWeBBGBGhe",
          "ljeLPPPahTWPQThf"
        ]
      },
      {
        "width": 16,
        "rows": [
          "llllllllllllllll",
          "ljhfgggjmghihhjk",
          "lidTYYagjCcfffhk",
          "leTYYYYXRTcfffhj",
          "leYYYYYYVRRXhfhi",
          "ldYYYYYWVRTReeVh",
          "ldWWYWVWVRRQddXh",
          "ldWWWWTWTVVRQQci",
          "ldYYYYWTTTRQRRef",
          "ldYYYWVVWTRVXXQf",
          "ldYYYYYWWTTRXXFf",
          "leWWWYWVVYVRedCh",
          "leWYYWWWTTXceeRh",
          "leTTWVVTRWafeeXi",
          "lfYYYTYehTVXVRfk",
          "leTTYYTdhFCCCCek"
        ]
      },
      {
        "width": 16,
        "rows": [
          "llllllllllllllll",
          "lecDDDBacccccbhi",
          "lcMAAAATTTTRAAdg",
          "lCAcaYYYXWVaaaBa",
          "lDAbXYWVWXXaaaGa",
          "lQBXXVWWYYaaaaGa",
          "lOBYVVWWWWYYaaBa",
          "lPBYWWWTVWXYaaGb",
          "lJBYYVVWVYYYaaGb",
          "lLBaYXYYYYYYaaBa",
          "lLBXXXYYYYYYaaBa",
          "lJBbaXYVVYYXhfBX",
          "lLBbaaYfeaabcdBa",
          "lPBaXYXeebbcccBa",
          "lfaAAAAadABBGDdf",
          "leXAAAAXcBBBBBdg"
        ]
      },
      {
        "width": 16,
        "rows": [
          "llllllllllllllll",
          "lnniihhjlhiiijnm",
          "lnnhiiijmiiiiinn",
          "lihihgZdmZZghiii",
          "ljiihgZgjZZghiii",
          "ljihZZZZZZZZdiZZ",
          "lmihZZZZZZZZdiZZ",
          "lhZZZZZZZZZZZZii",
          "lhdgZUZZZZZZZZih",
          "ljiSZZZZZZZZZZZZ",
          "lhgUZZZZZZZZZZZZ",
          "lhdZZZZZZZZZZZZZ",
          "lhgdZZZZZZZZdhZZ",
          "lighbZZZZZZZgiZZ",
          "ljidZZZdiZZZZZih",
          "lliZZZZgjZUUSShh"
        ]
      },
      {
        "width": 16,
        "rows": [
          "llllllllllllllll",
          "lcLNOTgeFHNObenV",
          "lYDGOSheOHBDYanF",
          "lLefgfihffcWDRiC",
          "lGeggehfffcXDQjC",
          "lAjdTTTWWWgfGQjC",
          "lAfcTWYXYYedMQjC",
          "lAcXWWYWWWaaDRjI",
          "lAcWWYXaaWddDQjE",
          "lBcaWWYYYaefBFiD",
          "lDdaYTTTTafeBFjE",
          "lCcffRffeghdACjC",
          "lGaccbccXaXRVXjE",
          "lEaWTNFECCGFTaiB",
          "lbSSWYTTTPPObanC",
          "ldVWYYRVQQQQcenX"
        ]
      },
      {
        "width": 16,
        "rows": [
          "llllllllllllllll",
          "lhbCCCHdiJHDBBfc",
          "leVQRVPehNQaaaXQ",
          "leBdccTefTXefeBA",
          "leBdcaRRRYXeeeAA",
          "leMRTVVYYYYWWWAA",
          "lePVVVWYXXWVYYAA",
          "ldAYTTWWYWYWbdWC",
          "leGWVTTTTWYYabYI",
          "leTYTTTWWYYWYYWT",
          "leTYWYTYTYYWYWYR",
          "leTYYYWYYWWWYYWR",
          "lePYWWWYYYYYWWWO",
          "leTYWYWWWYWWWWWO",
          "lhTYWWWWYWWYWSSD",
          "licaaaabbbbaacaV"
        ]
      },
      {
        "width": 16,
        "rows": [
          "llllllllllllllll",
          "lfLELKJOORQFCCck",
          "lcDGHNPTTTQQXXFi",
          "lXDDHJOORTPLccCf",
          "laHHJJNNOOOLbaFf",
          "lcHHIHJKOOOPLLOf",
          "lcHHJNHLJLLLLLOf",
          "lcGHEJOONLLOOOOf",
          "lcHHEJOIOOOOOOOf",
          "lcNJLJINOILNNOOf",
          "lcNJOOLOLLLONOOf",
          "lcOOOOONLJINIFQf",
          "lcNKKJLOOOOPccOg",
          "lcKNJHJNLPOQbcPh",
          "leNHHHHcePTTTRgn",
          "lfbXXXXfgaacccin"
        ]
      },
      {
        "width": 16,
        "rows": [
          "llllllllllllllll",
          "ljfaTOQaiABCFOhf",
          "ljTNGGMWhAABBBdd",
          "lfGdfdYTDccdeeMM",
          "lgBcecYTLccceePM",
          "lgBYWTVTTWYYBDAA",
          "lgBWXVWVWXYYITAA",
          "lfGWXYYYYYYXddTP",
          "lgBTYYXYaaYWcdTP",
          "lgBTXYYYYaYXWWWT",
          "lgBWYYYWVXYYYYYY",
          "lfBTYYYWWWWVYWWT",
          "lfBTXYYYYWWVYYYV",
          "lfBTXXYWVWVWWYVQ",
          "ljaaaXXYXYYYYXge",
          "ljaXXXXVVTVVYYge"
        ]
      },
      {
        "width": 16,
        "rows": [
          "llllllllllllllll",
          "lkhccccaaaacdeed",
          "ljcCIQQTTPTWWWWG",
          "lgCacdXVTWTWYYTG",
          "lgDccdaTWYYWWTTM",
          "lgGPQTTTTWWYYYSM",
          "lgDTTTTTTTYWYYSS",
          "lgGTRTRTRTWWYWTS",
          "lgETRTTRTTTWWWTU",
          "lfPPRRTTTTTTTWDA",
          "lgAPPTTTRTTTTWMA",
          "lgAPOORTTWYYTfDA",
          "lgPIOOTTTVabceDA",
          "lhSRTRTYacceedTA",
          "lkfaWDPYeCAAAacf",
          "lkfbbGSWeAAAAYcf"
        ]
      },
      {
        "width": 16,
        "rows": [
          "llllllllllllllll",
          "lBCEDDDBBBBALani",
          "lHHNOPPOPNGQRBjh",
          "lGJJJOOOOOCeFBhc",
          "lJLOOPPPOOKdCBie",
          "lNPOJKJKJJIENGig",
          "lILKOJJHDHIONBjh",
          "lNONHNHDEHHHeiki",
          "lOLKHMHHHHHHaeki",
          "lHJHHGHNNOOOQPjh",
          "lNJHDDHNKOLNOMhe",
          "lMHHGHKNKKKNHDfe",
          "lHJKHHMMJVRHHGfe",
          "lHNNHGGMMbaHGGfe",
          "lGHGGGDDBDDGGGhf",
          "lFCDDDDGDGGNTPig"
        ]
      },
      {
        "width": 16,
        "rows": [
          "llllllllllllllll",
          "lbBGMRcaVLQQXRnj",
          "lVKPTXcaaXXaXXni",
          "lObccccaaaaaaXni",
          "lXcccaaaaacccXni",
          "lccccbccbccccanj",
          "lccccccccccccanj",
          "lccccccccccccXnj",
          "lcccbcccccccfink",
          "lccbccccbcccijnk",
          "lbcbcccccccceeni",
          "lbcccccccccaeeni",
          "lbbbbbcbbccheenh",
          "lbbbbbbbafeieenh",
          "lcMMMMbaaaaahinn",
          "ldabbaccaacchjnn"
        ]
      },
      {
        "width": 16,
        "rows": [
          "llllllllllllllll",
          "lkcfXaaaXXXXXXXX",
          "ljVVCIONNNNIFIIF",
          "lhFFbcLOOLFEEEFF",
          "lhCFaaLONFECDDEE",
          "lhFFOPOOJEDEECEE",
          "liCFPOQPOEHEHEHE",
          "lkccLFLIIONIJHHE",
          "lkXcFFLFIIIEJJHE",
          "ljFCDEECEEEIJIII",
          "liFEDCFEEIILJJEE",
          "liFFCFFJJLLOJJHE",
          "liFFFcFFIIIEEEDE",
          "lhFFFbCCFFEEEHDC",
          "lkFCCFFVeFEEICCC",
          "lkQRFQRWgOQQLFFC"
        ]
      },
      {
        "width": 16,
        "rows": [
          "llllllllllllllll",
          "lkecXbcWgfXVQRch",
          "lkbLBMHDedGNRVcb",
          "ljBXcCDDeeOXeeeG",
          "ljBRcCDCccTaddeM",
          "liBDENJOPOOTTTTB",
          "liGNOOOPPOOOTTTB",
          "liUOPOOPOOOPOPOa",
          "liSPKOOOLOOQLLLW",
          "ljPPPNIOJJOIIFJN",
          "ljPNPIEHHEFEIJHH",
          "ljKNKICCDDECEEJJ",
          "liKNOJFEEDDEJFNN",
          "liMNNJIHHEEEIINN",
          "lkMHNPTTPOOOOPPS",
          "lkCCCQRVVVYWXXWT"
        ]
      },
      {
        "width": 16,
        "rows": [
          "llllllllllllllll",
          "lnXXVVVVXVVXXaaa",
          "lkQQLLLFFFHLLQRT",
          "liBQXcQIILOOQccT",
          "liBQabQHNOORObcT",
          "lhDIOONNOOORRRRW",
          "liCOPOONOPOOTRRT",
          "lhfaQONHHJJORRTY",
          "lhcXONHJFJJOQRTW",
          "lhHPPLJEHIIOQRTW",
          "lhHOOJJEGEFLQXcY",
          "lhMNLIJIFFFFFadS",
          "lhGKOONFeaHLcccN",
          "lhGMMPOJeaHFcccB",
          "lkMMMPPPSOLEDDFf",
          "lkTTSWWadbXXYRVf"
        ]
      },
      {
        "width": 16,
        "rows": [
          "llllllllllllllll",
          "lnjjhiigjihiijjj",
          "lniiiihdjigghjmn",
          "lnghhZZgZUUiighh",
          "lnghhZZiZZZihghh",
          "lnhdZZZZZZZZZiZZ",
          "lngdZZZZZZZZZhdZ",
          "lnZZZZZZZZZZZZdi",
          "lngdZZZZZZZZZZZd",
          "lnigZZZZZZZZZZZZ",
          "lngdZZZZZZZZZZZZ",
          "lngdZZZZZZZZZZZZ",
          "lngghZZZZZZZShgd",
          "lngghUZZZZZZSigZ",
          "lnhgZZZZhgZZZihh",
          "lkhgZZbdhgdbbhhh"
        ]
      },
      {
        "width": 16,
        "rows": [
          "llllllllllllllll",
          "leRQRVXccXXXVafk",
          "lbCDCDETQHDQQXen",
          "lDccXCFILIEadaAk",
          "lGccRDEINIJXccAk",
          "lHNOOIOIILOOKDAl",
          "lKOONJEJJOLLLIAk",
          "lKNIIHEIIJFLLXek",
          "lOOONNHFEILIFXak",
          "lKNIENIFHIEFFECj",
          "lHHHHEEFFLFFCCBj",
          "lEJECDCEFFFCCCAj",
          "lDEEEEECFQCCCCAj",
          "lDHFIEECLQCCCCAj",
          "lHJIIQLLFFECCCAn",
          "lLFLQQQLLILFFFLm"
        ]
      },
      {
        "width": 16,
        "rows": [
          "llllllllllllllll",
          "liiedcdgjeeeffjj",
          "lihRHBPbiaYRWWii",
          "lhFfefTacXXfffBX",
          "lhVhgfQYaVVfffAF",
          "lhafdVWWXVVTPGAA",
          "lhafeYYXXVVVYWAA",
          "lgIaYYWXXVYachYY",
          "lgXYXYXXXXXXadWa",
          "lieXYXXXVXXaaaYW",
          "lhaaaaXYXXXaaaTY",
          "lhaaaaaaaaaaabUY",
          "lhYaaabaaabbbcBP",
          "lhYbaaaaaabbbdAB",
          "lkfSMGGMBYaaYDbb",
          "lmdMGBBBBMNQGBWb"
        ]
      },
      {
        "width": 16,
        "rows": [
          "llllllllllllllll",
          "lcQYaXXaaaaaaXcm",
          "lCAADNOPOOORRRQm",
          "lNRPOPOOOOOQRRQj",
          "lPOPOPONJIILOFCj",
          "lPSPOPPOONLLQQBj",
          "lSTPPPOLONLLLFAj",
          "lSSTPPOOOOLLLBAj",
          "lPSSPPOLONILICAi",
          "lSSPOPPOOLILLFCi",
          "lSSSPPOOPQOFLOCi",
          "lSTTPPPOOOOQRIBi",
          "lSSSTPPOOOPOQaRj",
          "lSSSSSPOPOOTXcRj",
          "lPSTTTTPPPPFecXk",
          "lACCEFCCHHIFdaVk"
        ]
      },
      {
        "width": 16,
        "rows": [
          "llllllllllllllll",
          "lfcccaacceeeegjn",
          "lTTTTRRRTTWVWXcn",
          "lORTTRRTTTRTWVCk",
          "lPROQRTRQRQTWQCk",
          "lOROPTORQQQQLQCk",
          "lOQOOPTQRRQOLQBj",
          "lLOOOOOOOLQRRQCk",
          "lILOOOOLQQQQQQFk",
          "lJOQOOOIIILORRQl",
          "lILOINOLLLLQQTFm",
          "lLQLLIOOLOLOPaek",
          "lILIIIOQOQcabcak",
          "lLLLLOQQQRecabXj",
          "lORRRRQQQQLLQaan",
          "lPTTTTRIEDBBBFXn"
        ]
      },
      {
        "width": 16,
        "rows": [
          "llllllllllllllll",
          "liYABMGOXVTRRRde",
          "liYNPTTWXYVYXaXX",
          "lgCVVVVYYVVYceRR",
          "lhQVVXXVVTVVXcRR",
          "lhVYYVVVVRRRVVVR",
          "lhVVVVVVVVRRVVRR",
          "lgRVVVVVTVRRVVVR",
          "lgVVVRRVTTRRRVVR",
          "lgRVVVVRRRRRVVRV",
          "lhVVVVVRTRVRRVVR",
          "lhRTTRRVVVRVVVVQ",
          "lhFRRTRVVVRVXaVQ",
          "lhCVVVVRRRRRXcRF",
          "lkdLWVXXVYTTRRQC",
          "lkgccccccaaaXXac"
        ]
      },
      {
        "width": 16,
        "rows": [
          "llllllllllllllll",
          "liiijigjmghhhhmk",
          "liiiiidimgghhhjl",
          "lihhhgZZZZZddiii",
          "ljighgZZZZZddhhi",
          "lligbZZUUUUUgeZU",
          "lihgdZZZZZZSigZU",
          "ldZZZZZZZZZUZZdd",
          "lggUZZUUZZZZZZhg",
          "ljiSZZZZZZZZZZZb",
          "lfgZZZZZZZZZZZZZ",
          "lgdZZZZZZZZZZZUU",
          "lggggZZZZZZZZZii",
          "lhgghUUZZZZZUZig",
          "ljiZZZZdjZZZhggh",
          "ljiZWWZdjZZZhggh"
        ]
      },
      {
        "width": 16,
        "rows": [
          "llllllllllllllll",
          "lidSMMGMeAAABBff",
          "liVcdcYabWTcdede",
          "lhDfedaaaWVfhhbc",
          "lhCedaXXXXYeffTa",
          "lhCccYXXYYYYcfCQ",
          "liRXXXYXVVYYacYX",
          "liVXXYYXYVVYXWXV",
          "liCXYYYXYXXYXXXX",
          "liLXYYYXYYXXXYYV",
          "lhVYYXYXYYVXXYYX",
          "lhYYVYXXYYXXXcVX",
          "lhYYYXXXVVXXXcYX",
          "lhVWYYYVVVVVXbVX",
          "lkTTTRRRRTTRRRff",
          "ljjffffffhhhhhkj"
        ]
      },
      {
        "width": 16,
        "rows": [
          "llllllllllllllll",
          "lecFCCCCCECCCCEM",
          "lcQCCCCCCDDGNPSS",
          "lVCcaCCCCCCJOPSU",
          "lQCbaCCCCDCLPPPP",
          "lQBBBCCCCHIOPPPP",
          "lVCCCCCCDHIJOOPP",
          "lfeCDEFEHNNLNNOP",
          "lfcCDEFFINONNJJN",
          "laJHHEEEEHHFHHHM",
          "laHDDCCCDHHEJHIH",
          "lXHCGCDDDDCDHHJM",
          "laCaFCDCDDDCEEND",
          "lXCaQCCBBDCEIEFH",
          "leXCCCEcgGJOOQOO",
          "leXCFLQdhXaXXVRR"
        ]
      }
    ]
  },
  "face": {
    "palette": [
      "#974628",
      "#943b25",
      "#7d3e2a",
      "#773729",
      "#7b3328",
      "#6e302a",
      "#6a302a",
      "#6a2e2a",
      "#68312b",
      "#692e2a",
      "#682e2a",
      "#682e29",
      "#672e2a",
      "#63312b",
      "#53302b",
      "#6b2d29",
      "#692d29",
      "#692c29",
      "#682d29",
      "#682c29",
      "#672d29",
      "#672c29",
      "#622c29",
      "#5b2b2a",
      "#542b2a",
      "#4d2b2a",
      "#572828",
      "#4e2829",
      "#452f2c",
      "#452d2b",
      "#482b2a",
      "#432b2a",
      "#492929",
      "#4a2829",
      "#462929",
      "#432929",
      "#3d2f2c",
      "#3e2d2b",
      "#3d2c2a",
      "#3f2a29",
      "#3a2a29",
      "#342c2c",
      "#2e2b2d",
      "#2d282c",
      "#452527",
      "#3c2527",
      "#342629",
      "#342227",
      "#2e2529",
      "#29262b",
      "#2c2126",
      "#252229",
      "#221f25",
      "#1f1c23",
      "#1b1921",
      "#14121c"
    ],
    "textures": [
      {
        "width": 192,
        "rows": [
          "vBBBBBBBBAABBBBBBBBBBBBBCsBBAABBBBBBBBBBBBBBBBBBfbBBBBBBBBBBBBBBBBBBBBBBIjBBBBBBBBBBBBBBBBBBBBBAwEABBBBBBAABBBBBBBBBBBBBNtAABBBBBBAABBBBBBBBBBBAvsBBBBBBBBBBBBBBYXWCCCCCvCCBBBBBBEABEBBBBBBBBBBD",
          "vBEEEEEEEEEEEEEEEEEEEEEEDtECBEEEEEEEEEEEEEEEEEEEtsBEEEEEEEEEEEEEEEEEEEEEXoBBEEEEEEEEEEEEEEEEEEDEwLBEEEEEEEEEEEEEEEEEEEEEYvBEEEEEEEEEEEEEEEEEEEDEvtBEEEEEEEEEEEEEWWVEEDDFvCEDEEEEEEEEFEEEEEEEEEEG",
          "vBEUHPPPPPPPPPRRPPPPHGJEDtFFFJHGHHRTTQRTQSVVVVVVvsBPGHPPPPPPPPPPPPPRRRTVbtBBQQPPPHHHHHPHHHGGKMUGwWBUGHPHHRRRRRRRRPPRPPFThvBRJJJQHPRRRQPPPPHPRSSSvsCFGFPPPPPRRTTKWPQLVUVWtCBWVQPPPPPGPPFPPPLLJUEW",
          "vFQQPPPPPPPRQLQLLQHHHGHFItFGGJQJJKJSSSSSUUVVVVVVvtFPKPPRRRPPPPPPPHQQSVVVbnEFJQPLLQHGHGGGGGJSMKUHwXEKJPPPPRRRRTTRRRRQRSTVsvPJKLQPQQQRQQSSRQSTTUUVvsPHHHPGGHJLSUUSVSLSVVVWvFFUVRPPPPPHPHPHHQSLUMFa",
          "tMQQHHHLLSSSTUMKKQLJJGGJNtPUMKKMMKKKMSMUUUVUUVVWvtTTSJQHJJQPQHJQQQMSSUVVbnPRJJSKJSKKJKJJKKJKMMUHuYHSKQQLSSSQTRSTTTTRSSTVsvPTUUKKKUSJJSSSJJJSVUUVvsLJJJJLLJKJSUMSTLLUVVVWtUVUVQQQJJGHJJGLLSSKUMVY",
          "tIPPQQQTSSJSLMUMSJJGGGGGItHVUMSMMKKUUMLUUUUMKUVVttVUMQJLHHHQLLQLHGLLSSUVYnHQKSSJJSJJJJHJSSSMMMMFwaSKKKQLQTTQQSQHLQQJHJQVsvPVUVSSUSSUSKQLLSSUUUMUvsUSKJJJJJLJKSLKQLUVVVUWtSVVVSRQHGHJHJJJJSSKUVVa",
          "tGHHQQQQSSVSQLUSJGGGHGGGItPSLKKKSKSJKSMKKUSJSVVVtsVVUJSSHPQPQJHJHGJGHLQQanHJKJSSSQKJJJKJKIJKUKLFraJKJJJJLHHHQHHHHHJHJLQQsvPVUVVSSQQQTUKKQLQSUUMUvsKKKJJJJJJLJJJSSMSSSUUWtRTUUQQJHHPQQJJHGJSSUUVa",
          "tIQPQJJKKSUKSMUSSJHHFFFFItPTSSMMKJHJKSMMUKSUSTVVtsUMUVVTQHHHHHPQQQHJJHHHYnHQSQJKKQHJHJJGJJKKKJJFwaSKHJJJHQHHJHJQQLJPJHPPsuFTSTTQRSKJQTVVSJLSUMMSvhJJJGJJJJKKLLQKUUUKSQLWtTTVVQQQJQPQJJKJJLUKMUVX",
          "nIHHSSJUVUUUVUUMJGGFFFFFItPQLKSKJKJJJKUUMMKMUSTVtsKUUUUJPQHHHHGGHLJJHPPPaoHLSSQHHHHGGHJJKHJKSJJFraQQHHQHHJHJQHQJGLQHHGHPsuFRQRQQKSSKLSSSSLLSUUMVvsGGKKKKKKLLLQHGHKQRTQLWtRTUVSSJJLQQSSQJKUUMSTVa",
          "yIPQSUUKWUVUTQXUGPMXFJXFNyFPHXMSJKJJLUNMSUKKYVRRyyJKKUMYHPPPPPPPPNYYGPPPbyPLSJHHHHHJGGHHYOHGSVQFwYPQQQHLHJQQJHUMJPYbFKVFguFPQQSTTUSTSUSULQSJXMUUytLUKUUMUSKSSSXaPVSJVWPW1VVaXQWWQSQKMWQSUYbQLQTb",
          "yIPQSMMUWUULPRXWPHMNFFMFNvFFLWMJJKMMUVXWUUMMaWQPvyHKKMWaGJHHPPFFFMXXGPPPZuFKLJJJGGJJJJJHYYHGSUSFubFQHJLLQQQSQJUMUFabFKVFguDRSSUSSSSUUSSJLLSKXWWK0tWUNMMMKMUUUSXaHMMRVWKXzWNaXUWWIMVUUWSSUXYHHQRY",
          "3bWPLQSRTVSPPPYWHbWHFFFst3aXUMULKUVWWWZWVVUQHFLa21aaaXXaaXPPPPPPFFFPPFPay3baJJQHGGWUUVUMMMJJPPNb3ysPQSSTTTRTVVVSTRRPFFRay2sQVVVTTXaXUVPPQSSUVVWb33XXXXXXXXXaaaaXWbbRSMbs3ssUVWVVstVVTVVSTIJFPPav",
          "3ihbZZbbZieZYYgZhjshhhsvy3tthgZZbiiigZghhhbbbZZt21tttttuuotttjZYbZZeeZZty1vnhhggeefffgeZhbZZZZij3ytgZeZgZhZihbhbYYbbYbbtyytigggggjfeZZOYYYZYYYZt21bgijjjjnnmiijjjnmjtttv3vttnnssvvvssjhbbbZZZgsy",
          "3ywvwwwup10xzvuwwwuuuvy13310wwwww00zwuuuuuuuvvy11110yyyzwyyrwyvuuwuwyy00000zzzyywyywwwuvutuuuvvy32ywwuuuux1zwvvuutttutu310yyvuuvwzzOvvvvvuuupup122wwwwywwwy2wwwwwrwryy012110zzzzz031y1yvvvvvvyy1",
          "SAAACCCBAattDACCCCCCCAACAACAAACCCDa2eAAAAALaACCCAABAAFFE2vA2yCAACCEtsAABBBBBBBCFCCa13ABACBBCFAACCCDACDDDDDI3DAACCACEBAAFAAACCAADCYysYCAAADDCCAAFAAAAAAADDWY3NAACCCBaAACCCBADCFFFFDW31FAACCCbCAAA",
          "hCCCDFFFFbtZDCGFDGFGNCBFFDFDDDIIINN1ZACCCDXbCDDDCCEDDNWX2vC0gCCDMNIvtECDDDDDDDNXNXY03ACCFFFMNCCFFGICINNNINX2DCCDDDFMGFGaDDDFDIINItyYYFIDDIIFDCFWFDCDFFNXIYO3NCCGGILsCCFDDDDFDWXXNNW1vDCFIINtCADC",
          "tFWWXXXXNXOIAYXXMXWaYNDXXXXWWbYYYXN0ZCaXXXtsDMMMKMUYYbbb2yFyNCYibhhytCIGIMMSFXhYbbby1AYaaaaheDMWWWWRZeegOij0CDXXXXXXXaaYNXXNNjeYYfuFWNOZbZZaGaXaaXDWNbhYFbezDCaaaaYsNFWWWMWWWYYYYYXytAbXWbX1CCWW",
          "tNWWNbXXZhfXMYXWNaYYXYaNNWWbhYhgYZi0sXXXXXihWMVYWSVYnXbh2yUysWZgaYYyuWXbIFXXabiYbhhy1UZbaaXieOWMMNWbZeieiij0NNaXXXhihXXnXWXhiOYZgy0GYXiZXXXYiWXsXXXXXZiObiZzNWXaXbbgbgMWMMMssXYYYhs0nFYYYYX0DIXW",
          "gOIIIeXXegjbWbXMXaYbWbZWNNNYbYijXjj0tXaaXajiXXWgWHKXZXbj3yaytNbZXYayvXXhNIaXXhgbbhby0FZhaXWgZZYMKMMeeiiijjj0XabaaXjjiXWsXNWgeNXZhw1NaGiZXYXYjXXgXXXXXZjYgeZzOWaaXhbbZgUWWMNbhXaabis0nIXYYYa0GDYX",
          "jOXIZZeeghjbWhZZhbYXZZhMXZYZZgjjijj0tWsjsXnjXYbhWGbeeeej20sythgegYXyuYXbbYXYiigghgbw0aZZgggeeeYNZXUidijjjjjzhabaXjjjibaWbgXgeeeZgw0NbheeeeZbffgeZZWYgeeZeeZzYXbbbbhhgeWWWXXgihiggisytWiYXXa1aXaX",
          "dOONOZeZZZfZXZZZZZYXgZeWYZYZZijnjid0tNjfjXtnXhbhXWhieeed20sythgeeOXyuZZbgZOYighgggZy0YZggiggigYXeYNfifdfeeezZYbYXnjjjibVsnYeeeeeiw0NZeeeeeZZffieegXZeeeeZecxZYhhhhgggeWXWXYggggggiiytYgOXXX1bYYa",
          "0ZeZZZmZeinfZZZZghggggeNYZZeeOouidd0uZedfiffnZbbijgjjgju20iyuhgfOfnywghbgiiiegggZZrx0beegggntgeeeiieeieeeed2ZbZfnjjjjjjTtweeeedodwzideeeeddddfeigggeeeenZmm1eZbhbghhhggiiiiiieeghewzubYepoozZbge",
          "wZZZZemedtothhghhggggggXgeegiZuuedf0ueeeeiffjibhifgjnjtu31lxufdldnt20sggjniiiggfdcrx1heiiiiuuiigeeeefmdeeej2fggffjjjjjnYvwoiijfpoz0tleeeeeeeeeeefieeifnonuo2jjiiZeeegghggeggiijjefu0ufinooowiegg",
          "pcOOZeffow11thhhhghbhhgsigZZZjuweuw31sZbZZejjisinoZZittu32p2xlfnttt32ihgowZZZZepuww33tnisssywhZZZZZZnueeeqx3xtZjifddfifttt2ejntou1zyuZeeeeeeZZZZyvZZZouuuyv3vttsZtyneZZghghZhgyuuyw30oooooo3vvgg",
          "xxruuwwww22222yyyyyyyyyyvyyuuwwxy02321000y000011000wuyyy33x1110001222yyywrwwuuuz011230y0yy020ywywwwuwwww001321000y02uuyy002wwwyz033yywuuuwwwwyyyzzywwwxyz333yyyyyyzyyyyyyyyyyy1101132ywyxz0210vy",
          "122110002322332222122221112100001333333322223333333211012211222233333110zx212222233222331233211101121111222332322223222221210111133y220112222222012221112333222211122322221112222333322222233321",
          "3OCCCONNNIIALN2tIIIIIFDv23iIDDINlkkACIIIINOZNOf32ydDCDIDmOCAACN1CINNNFDZ12OmCINNNcNCACCM22FNNIOe30hDDDDIINNAAFvvNNNNZOOy02OCCCCCIIIbCANNNNINNNNt32gDCDIDNOjAAINOoNIYOZuy3OhINNXXNNICAIINNNNNNNv2",
          "2NZOOOOZcccIns2wZZZZZZZk01OOOOZjkpxINZZZedffccl30rOZcdcepfNNXOe0XOOZZZYdy2OOccccccOOFOZf1yYZZZde3tNOOOOZcccXOZyuieeidfni01NOOOOOOcO2CCcOZZeededf3yOZOOOZclpDIOenoZZffjtu3XNZccddcdONIZddddddddmy",
          "0DOfdddfffdFtt2wjnnnfdccz0DefnnnmpzNOnnnnnnnflf2ypIfmmolwmccddl0Ocdfffffy1NXmmmlklcZIfnnuunnnffd0jGfcdffnnmNZeyunnffffney0Ifffdddlc3ONlllmlnnnmf3vNflmmmmouNOioomlffnnfm2IIllllllleOInoooommmmlw",
          "0Oddddddddcnoo2wnnnnnmuk01Zcddffmqzjnnmnnnnnfou2zqflklmlzwcdddl0cdffnnffw0ffkkllllffnnnn00cddffc0ofcccdcflfejjyyffffdllmyzZcdfdccpu3mZlnnnllmllc2vecllnnnownfnmmnnffnnno2dclkklllcdfiloooommmkrx",
          "0Odcdcdccdcloo2rtnmmmowk11dlcdfdopxfnllnfollloo20xkkkkml0xfcccl1cfnnnnnlu0cckkllmmmmmmnf0zcdddfc0ufldcddcdffffyznnfffflmwzZccddddrq3pcnnnmlllllc1uflllmlnoyfflllllnlnnnu2ccllllllcdddcoooooomkqx",
          "1cfllkkkkpkkwz2zooooookx22nppcoppx1ollnmooopkow30xrommoo0xllllp1ouwouumkr0cckclommmmmmowzxcdfnnl2yopfccccckully2louumpppxzcmlrolwqq3xummmmmlklkk2wfllllllozcdlkfmmmnoxxz2klpolpxkcqpeoommoomok01",
          "1kkkkkkkpppkzx2zuooooppx22pqpkppqx1pkklpqpppppx21zqppouo0zkkkkr1pqqpqqkpx1kkkkkppppommpy0zllmnok2xppkklkkkkqkk11puqrppppxzppkqporrq3zrpomokkokkp2xmomlkkkpzqclkkokpmqxxx2ppppkpxkkqqfpokkooooo11",
          "1pkkppppppppzx20xuuuprxx22rqqqqqqx2ppqrqrqrrqz0212qrxxqp0zrqqpz3pqqqrqqqz2ppqqqpqxqpkkpp20prxxxq1xpqqqqqqpppkk2xqqrrqpprz1kqqqqqqrq3zxrxroppkppq2xrrppopqrxxcckqrxxxxxxx3rqppxrxxrrxpqpppppxrp11",
          "3qrrrxrrrxxx2332xxrrxxxz33zrqqqqq02qrxqxzqxxxz2322zzxxxx0zxzzz13xrqqqqzz13zzqqqqqq0xpprz32xxxrxx31zqqqqqqxx2pu30xrqpprx223xqqqqqqqq320rrrxxrrxz131xrrrrqrx2xpqqxxrxrxx213xxxxxxxxxxxq1qqqrrxxr22",
          "3xxxxxxxxxxx3332xxxxxxq2332rrrrrr02xxxqz1pxxxz23332zxxxz000010231rrrqq002311qqqqpq1zppw132zzxrxz330pqqqqqxx3ww32xxqqpxx3332qrrqqqrq333rrxzzzzzz232xxxxrrrr3zpxxxxxxrrr213xxxxxxxxxxxq3qxxxzxxx33"
        ]
      }
    ]
  },
  "cap": {
    "palette": [
      "#ee8b24",
      "#ee8824",
      "#ed8624",
      "#e98923",
      "#e88723",
      "#eb8424",
      "#e68422",
      "#e77f25",
      "#e07c27",
      "#db7124",
      "#d96e23",
      "#d86d23",
      "#d76c22",
      "#d16e24",
      "#d16c24",
      "#d06b23",
      "#ce6b24",
      "#d16a23",
      "#cf6a25",
      "#cf6922",
      "#ce6925",
      "#ce6923",
      "#ce6824",
      "#cd6925",
      "#cc6926",
      "#cc6825",
      "#cd6923",
      "#cd6724",
      "#cb6726",
      "#c86524",
      "#ae5223",
      "#743224"
    ],
    "textures": [
      {
        "width": 192,
        "rows": [
          "fJJJKKKJJJJJJJJJJJJKKJJMcfKLMMRMMMMMMMMMMLKKKKKKffJKLMMMLLLLKKLLLLLLLKJJefJKKLLLLLLMMMMLMMMLLKJHfeJKLLLLKKKKJJJJJJJKKKKKffJJJKKKKKJJJJJJJJKKMKKJffJJKLLKKLLLKLKKKMRRMMLdfJJKLLLKKKLLLKKLLLMLLKMe",
          "fJSSUXUUSSSSSSRSSSUQVVVaYfRbbccccccZZZZZYYXXXaaaffObddcccZbbZZWWQVZYYcZOefMbcccccccZZYYYcZccZZXIfeIbZccYXUUUSSSSSSSUUccdefMSSUXXXQSSSSSSSSSWWXVKffTWZZYZUZZZZbbWUdddddcdfKTVWZZZZZUUXZZXZZYYZbTe",
          "fFJSSSSSSSSSRRRSRRTTTTVIIfHJcdcZZZZZZZYXZXXUUQbIeeIddddcZbbWWbbbbWbccYcHdfMbcccccZZYYZZZZbbbZbQFeeIbbZZZWWSSSSSSSSSSUUcQefHaaXUUUSSSSSPSSRTVUadHfeIRaUUVVWbbZbabWeddddddeCAbWUUSSVVWWUWZZZZZZbKd",
          "fFJSSOSOOQSSSUTTTRPRRORIIfHJcdccYYYYXXUUXSUXXVVHeeIdddcZZWXXUUXaUVVXYYcFdeTRccccYcYYYXXUaYYZZWNCeeGdcbbbWSSSSSOSOSSSSSYNeeHRUaXUXUSQSSUSSQVUUQaHfeIRSUXVaXXXSSTTaddddddcfCDcZUSSRSRRUXXaaZZZZZJd",
          "fFIROOOOPOPPRSRRPOONNNNEIfHJcZZZZQQQSOOOQQQQQQaBeeHaZZWWSSVSPSSQSQQXYYYFdeAFYYYXXXXQQQXQaaaXaSNAedEcbbWWSSSONONONOOSONaAeeFNNSSSSQPOPPPPQPPPPPQGfeHRRSUaaQQPTTPPNeeddddJfHDaUUQOOOOOQSVaaaQUYbGP",
          "eBIRPRPOPPPPRRMRMRMMMMNEHfFJaaXaZaaPOMNOPPPPTTTCeeGTaaQPPRRRPPTTPPTTTaaFdeAFOQXQSPPOPPPTVTVVTONAedDaTTTTTTRONNMNNNMMNNNAeeBMNNNOPPPRRPPPPPPPPNNGfeHRPRTTTRRRTTTTJeedddYIeCATPOPOORTTVTTTTTPTTaHM",
          "fNIBDDDEDBBAAAAAAADDDDAGNfMNHGGGGGGEEEEEEGGGGGFGffEGGGGEEEEEDDDDDDDEEEFGefBGHGGGGGGGGGGGGHIHHHHBfeDEGGEEEDDDDDDAAAAAAADEefAEDEEDDDDEDEEEDDDDDDDGffFEEEEEDDEEEEFAeffGGGFIfeeACEDDDAAGJGGEGGGGHHHe",
          "fIFABBBBBBAAAAABBBCCCCBEIfJJHHHHHHHFCCFFFFFFHFFFffAGGGFFFFFFFFFCCCCCFFFFefBHHHHFFFFFFFHHHHHHHHIBfdADCCCFCCBBBBBBBBBBCBCFefAEDBBCCFCCCFCCCCCBBCECffCCFFFCCFFFFFFBeffDECEIfdeACBBBAAAGJCFFFFFHHHHd"
        ]
      }
    ]
  }
};

const cache = new Map();

/** Decode once into opaque native-resolution canvases; no asynchronous images. */
export function referenceTextures(material) {
    if (cache.has(material)) return cache.get(material);
    const { palette, textures } = DATA[material];
    const colors = palette.map(hex => {
        const rgb = parseInt(hex.slice(1), 16);
        return [rgb >> 16, (rgb >> 8) & 255, rgb & 255];
    });
    const result = textures.map(({ width, rows }) => {
        const canvas = document.createElement('canvas');
        canvas.width = width;
        canvas.height = rows.length;
        const ctx = canvas.getContext('2d');
        ctx.imageSmoothingEnabled = false;
        const pixels = ctx.createImageData(width, rows.length);
        for (let y = 0; y < rows.length; y++) {
            for (let x = 0; x < width; x++) {
                const rgb = colors[ALPHABET.indexOf(rows[y][x])];
                const i = (y * width + x) * 4;
                pixels.data[i] = rgb[0];
                pixels.data[i + 1] = rgb[1];
                pixels.data[i + 2] = rgb[2];
                pixels.data[i + 3] = 255;
            }
        }
        ctx.putImageData(pixels, 0, 0);
        return canvas;
    });
    cache.set(material, result);
    return result;
}
