"""Bake the supplied 1897x829 style reference into small native-pixel materials.

Development-only tool (Python + Pillow). The browser needs neither Pillow nor
the reference PNG: all palette indices are embedded in referenceArt.js.
Usage: python tools/build-reference-art.py path/to/reference.png
"""
import argparse
import hashlib
import json
from pathlib import Path

from PIL import Image


FLOOR_CROPS = [
    (194, 291, 39, 39), (194, 212, 39, 39), (233, 212, 39, 39),
    (272, 212, 39, 39), (194, 251, 39, 39), (233, 330, 39, 39),
    (233, 408, 39, 40), (233, 566, 39, 39), (272, 251, 39, 39),
    (551, 251, 39, 39), (473, 369, 39, 39), (904, 448, 40, 39),
    (233, 645, 39, 39), (272, 645, 39, 39), (550, 330, 39, 39),
    (511, 408, 39, 39), (904, 291, 39, 39), (904, 566, 39, 39),
    (1103, 173, 39, 39), (1182, 173, 39, 39), (1340, 173, 39, 39),
    (1379, 173, 39, 39), (1498, 173, 39, 39), (1458, 251, 39, 39),
    (1498, 369, 39, 39), (1537, 408, 39, 39), (1458, 645, 39, 39),
    (1419, 684, 39, 39), (1458, 724, 39, 39), (1419, 566, 39, 39),
]
ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'


def sample(source, crop, size):
    x, y, width, height = crop
    return source.crop((x, y, x + width, y + height)).resize(size, Image.Resampling.NEAREST)


def encode(images, colors):
    # One palette per material removes the reference's near-identical RGB
    # values. No dithering, blur, synthetic noise or per-pixel randomness.
    strip = Image.new('RGB', (images[0].width, sum(image.height for image in images)))
    y = 0
    for image in images:
        strip.paste(image, (0, y))
        y += image.height
    indexed = strip.quantize(colors=colors, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.NONE)
    palette = indexed.getpalette()
    data = list(indexed.tobytes())
    used = sorted(set(data))
    remap = {old: new for new, old in enumerate(used)}
    rgb = ['#' + ''.join(f'{v:02x}' for v in palette[i * 3:i * 3 + 3]) for i in used]
    textures, offset = [], 0
    for image in images:
        length = image.width * image.height
        rows = [''.join(ALPHABET[remap[p]] for p in data[start:start + image.width])
                for start in range(offset, offset + length, image.width)]
        textures.append({'width': image.width, 'rows': rows})
        offset += length
    return {'palette': rgb, 'textures': textures}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('reference', type=Path)
    args = parser.parse_args()
    source = Image.open(args.reference).convert('RGB')
    if source.size != (1897, 829):
        parser.error('Expected the supplied 1897x829 reference; crop coordinates are specific to it.')

    floors = [sample(source, crop, (16, 16)) for crop in FLOOR_CROPS]
    for tile in floors:
        # Single-pixel shared joints: adjacent tiles never double the grout.
        # The chipped stone edge within each tile stays exactly as sampled.
        for p in range(16):
            tile.putpixel((p, 0), (54, 52, 46))
            tile.putpixel((0, p), (54, 52, 46))
    materials = {
        'floor': encode(floors, 40),
        'face': encode([sample(source, (1082, 35, 493, 92), (192, 36))], 56),
        'cap': encode([sample(source, (1082, 17, 493, 18), (192, 8))], 32),
    }
    digest = hashlib.sha256(args.reference.read_bytes()).hexdigest()
    output = Path(__file__).resolve().parents[1] / 'app/browser/referenceArt.js'
    header = f'''// Reference-derived pixel materials. Generated by tools/build-reference-art.py.
// Source: user-supplied dungeon reference, 1897 x 829; SHA-256 {digest}.
// Native pixels, bounded palettes, nearest sampling, no dithering or runtime noise.
const ALPHABET = '{ALPHABET}';
const DATA = '''
    decoder = ''';

const cache = new Map();

/** Decode once into opaque native-resolution canvases; no asynchronous images. */
export function referenceTextures(material) {
    if (cache.has(material)) return cache.get(material);
    const { palette, textures } = DATA[material];
    const colors = palette.map(hex => {
        const rgb = parseInt(hex.slice(1), 16);
        return [rgb >> 16, (rgb >> 8) & 255, rgb & 255];
    });
    const result = textures.map(({ width, rows }) => {
        const canvas = document.createElement('canvas');
        canvas.width = width;
        canvas.height = rows.length;
        const ctx = canvas.getContext('2d');
        ctx.imageSmoothingEnabled = false;
        const pixels = ctx.createImageData(width, rows.length);
        for (let y = 0; y < rows.length; y++) {
            for (let x = 0; x < width; x++) {
                const rgb = colors[ALPHABET.indexOf(rows[y][x])];
                const i = (y * width + x) * 4;
                pixels.data[i] = rgb[0];
                pixels.data[i + 1] = rgb[1];
                pixels.data[i + 2] = rgb[2];
                pixels.data[i + 3] = 255;
            }
        }
        ctx.putImageData(pixels, 0, 0);
        return canvas;
    });
    cache.set(material, result);
    return result;
}
'''
    output.write_text(header + json.dumps(materials, indent=2) + decoder, encoding='utf-8')
    print(f'{output}: {output.stat().st_size} bytes, {len(floors)} floor variants')


if __name__ == '__main__':
    main()
